[build]
  command = "pip install -r requirements.txt"

[config]
  sample = "sample.env"
  output = ".env"

[post-build]
  message = "Run `python ./app.py runserver localhost:8080` to get up and running."