[meta]
  title = "Django Transcription Starter"
  description = "Get started using Deepgram's PreRecorded Transcription with this Django demo app"
  author = "Deepgram DX Team <devrel@deepgram.com> (https://developers.deepgram.com)"
  useCase = "STT"
  language = "Python"
  framework = "Django"
  
[build]
  command = "pip install -r requirements.txt"

[config]
  sample = "sample.env"
  output = ".env"

[post-build]
  message = "Run `python ./app.py runserver localhost:8080` to get up and running."
