[meta]
  title = "Prerecorded Django Starter"
  description = "Basic demo for using Deepgram to transcribe files with Django"
  author = "Deepgram DX Team <devrel@deepgram.com> (https://developers.deepgram.com)"
  useCase = "Prerecorded"
  language = "Python"
  framework = "Django"
  
[build]
  command = "pip install -r requirements.txt"

[config]
  sample = "sample.env"
  output = ".env"

[post-build]
  message = "Run `python ./app.py runserver localhost:8080` to get up and running."